# Generated by Django 5.0.4 on 2024-04-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fabrict',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
